### ISSUE TITLE
Very Long Chains

### ISSUE THREAD

**Issue by tomitrescak** [lexanth/python-ast#1]
Hello, thank you for the amazing library!

 I'm just curious why the grammar is creating such a long chains of contexts. I have a simple expression `1+1` and this is just a snapshot of the tree (I just visualise children of each context):

![image](https://user-images.githubusercontent.com/2682705/127156559-b98b74fb-bc92-483d-82e2-3e5f88e8fc80.png)
![image](https://user-images.githubusercontent.com/2682705/127156611-4cfa159f-04ee-424d-bc2f-60a6cb91640d.png)

You can see how many contexts are built in order to reach the arithmetic expression with many redundant nodes in between. I worked with java-ast and there were no redundant nodes.

**Comment by lexanth** [comment]
The actual python parsing is all antlr (grammar and library), so it might be better for discussion over there. https://github.com/antlr/grammars-v4/issues/2251 seems to discuss the need to optimise the grammar to avoid this sort of chaining, for example.

**Comment by genderev** [comment]
How did you even visualize this snapshot? I can't figure out how to use this library.

**Comment by tomitrescak** [comment]
@genderev I used my own visualisation code for this using vega. This library just builds the AST, nothing else.
